version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Back/Dockerfile
        ports:
            - "8000:8000"

    frontend:
        build:
            context: Front/pose-corrector
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend
